# Generated by Django 5.2.1 on 2025-05-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tax',
            old_name='tax_persentage',
            new_name='tax_percentage',
        ),
    ]
